
version: '3.2'

networks:
    cnrl:
        external: 
            name: cnrl

services:

    ca_org3:
        networks:
            cnrl:
                aliases:
                    - ca_org3
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == node01
        image: hyperledger/fabric-ca:x86_64-1.1.0
        hostname: ca.org3.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org3
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4a1914c7f6024155fba08fffc0c77784517547b7e2e1c41c1294fcf2b1f2e065_sk
        ports:
            - 9054:7054   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'

        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == node01
        image: hyperledger/fabric-couchdb:x86_64-0.4.6
        hostname: couchdb0_org3
        networks:
           - cnrl

    couchdb1_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == node01
        image: hyperledger/fabric-couchdb:x86_64-0.4.6
        hostname: couchdb1_org3
        networks:
           - cnrl
